### ISSUE TITLE
fc when start crDroidSetting on Samsung Galaxy Tab 5e (gts4lvwifi) build.

### ISSUE THREAD

**Issue by FraEgg** [crdroidandroid/android_packages_apps_crDroidSettings#525]
Hello, i have build a own crDroid for my gts4lvwifi device. The crDroidSettings App has fc at start

Sources:
https://github.com/FraEgg/android_device_samsung_gts4lvwifi/tree/10.0-luis-los
https://github.com/FraEgg/android_device_samsung_gts4lv-common/tree/10.0-luis-los
https://github.com/FraEgg/android_kernel_samsung_sdm670/tree/10.0-luis-los
https://github.com/FraEgg/proprietary_vendor_samsung_tm/tree/lineage-17.1

Logcat:
```
02-16 11:10:37.258 D/SettingsActivity(11081): Starting to set activity title
02-16 11:10:37.258 D/SettingsActivity(11081): Done setting title
02-16 11:10:37.258 D/SettingsActivity(11081): Switching to fragment com.crdroid.settings.crDroidSettingsLayout
02-16 11:10:37.258 D/SubSettings(11081): Launching fragment com.crdroid.settings.crDroidSettingsLayout
02-16 11:10:37.258 D/audio_hw_primary(603): select_devices: done
02-16 11:10:37.260 D/SettingsActivity(11081): Executed frag manager pendingTransactions
02-16 11:10:37.272 V/msm8974_platform(603): platform_set_channel_map channel_count:2
02-16 11:10:37.273 D/msm8974_platform(603): platform_set_channel_map mixer_ctl_name:Playback Channel Map13
02-16 11:10:37.273 D/msm8974_platform(603): platform_set_channel_map: set mapping(1 2 0 0 0 0 0 0) for channel:2
02-16 11:10:37.280 W/TileUtils(11081): Found com.android.settings.Settings$DataUsageSummaryActivity for intent Intent { act=com.android.settings.action.SETTINGS pkg=com.android.settings } missing metadata com.android.settings.category
02-16 11:10:37.285 W/TileUtils(11081): Found org.lineageos.lineageparts.applications.ExpandedDesktopSettings for intent Intent { act=com.android.settings.action.IA_SETTINGS } missing metadata 
02-16 11:10:37.297 D/ConstraintsHelper(11081): construct key=status_bar_clock available=true
02-16 11:10:37.299 D/SettingsActivity(11081): No enabled state changed, skipping updateCategory call
02-16 11:10:37.301 W/ListPreference(11081): Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
02-16 11:10:37.302 D/ConstraintsHelper(11081): construct key=use_old_mobiletype available=true
02-16 11:10:37.303 D/ConstraintsHelper(11081): construct key=data_disabled_icon available=true
02-16 11:10:37.304 D/ConstraintsHelper(11081): construct key=show_fourg_icon available=true
02-16 11:10:37.306 D/ConstraintsHelper(11081): construct key=roaming_indicator_icon available=true
02-16 11:10:37.308 D/ConstraintsHelper(11081): construct key=bluetooth_show_battery available=true
02-16 11:10:37.314 W/ListPreference(11081): Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
02-16 11:10:37.315 D/ConstraintsHelper(11081): construct key=status_bar_battery_text_charging available=true
02-16 11:10:37.317 D/ConstraintsHelper(11081): construct key=double_tap_sleep_gesture available=true
02-16 11:10:37.319 D/ConstraintsHelper(11081): construct key=status_bar_brightness_control available=true
02-16 11:10:37.321 D/ConstraintsHelper(11081): construct key=qs_quick_pulldown available=true
02-16 11:10:37.323 W/InstrumentedPrefFrag(11081): Screen title missing for fragment com.crdroid.settings.fragments.StatusBar
02-16 11:10:37.324 D/AndroidRuntime(11081): Shutting down VM
02-16 11:10:37.326 E/AndroidRuntime(11081): FATAL EXCEPTION: main
02-16 11:10:37.326 E/AndroidRuntime(11081): Process: com.android.settings, PID: 11081
02-16 11:10:37.326 E/AndroidRuntime(11081): java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.preference.Preference.onPrepareForRemoval()' on a null object reference
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at androidx.preference.PreferenceGroup.removePreferenceInt(PreferenceGroup.java:298)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at androidx.preference.PreferenceGroup.removePreference(PreferenceGroup.java:274)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at com.crdroid.settings.fragments.StatusBar.onCreate(StatusBar.java:115)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2596)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:831)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1853)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1686)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:299)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:230)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1238)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1086)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1616)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.View.measure(View.java:25104)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.View.measure(View.java:25104)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.View.measure(View.java:25104)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.View.measure(View.java:25104)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:995)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.View.measure(View.java:25104)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.View.measure(View.java:25104)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.View.measure(View.java:25104)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.View.measure(View.java:25104)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.View.measure(View.java:25104)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:742)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.View.measure(View.java:25104)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3083)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1857)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2146)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7781)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.Choreographer.doFrame(Choreographer.java:726)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.os.Handler.handleCallback(Handler.java:883)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.os.Looper.loop(Looper.java:214)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at java.lang.reflect.Method.invoke(Native Method)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-16 11:10:37.326 E/AndroidRuntime(11081): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
02-16 11:10:37.328 I/DropBoxManagerService(1086): add tag=system_app_crash isTagEnabled=true flags=0x2
02-16 11:10:37.329 W/ActivityTaskManager(1086):   Force finishing activity com.android.settings/.SubSettings
02-16 11:10:37.337 W/ActivityTaskManager(1086):   Force finishing activity com.android.settings/.Settings
```

**Comment by followmsi** [comment]
Same problem on Google Pixel C .. Nexus 7 2013 (flo) seems to be affected as well.

All affected devices are "wifi-only" devices (tablets).

Thanks

**Comment by 12paq** [comment]
Logs of borked CRsettings crash on wifi only device "dragon"

time: 1580476773982
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.preference.Preference.onPrepareForRemoval()' on a null object reference
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.preference.Preference.onPrepareForRemoval()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.preference.Preference.onPrepareForRemoval()' on a null object reference
	at androidx.preference.PreferenceGroup.removePreferenceInt(PreferenceGroup.java:298)
	at androidx.preference.PreferenceGroup.removePreference(PreferenceGroup.java:274)
	at com.crdroid.settings.fragments.StatusBar.onCreate(StatusBar.java:115)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2596)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:831)
	at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197)
	at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080)
	at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1853)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
	at androidx.fragment.app.FragmentManagerImpl.executePendingTransactions(FragmentManagerImpl.java:183)
	at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:567)
	at com.android.settings.SettingsActivity.launchSettingFragment(SettingsActivity.java:360)
	at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:268)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more

**Comment by FraEgg** [comment]
Hello,

Workaround commit to use crDroidSetting on devices without telephony:

https://github.com/FraEgg/android_packages_apps_crDroidSettings/commit/6c4923f8a4928c0b89e863bb87878d3103b8a2ec

Cu Frank
