### ISSUE TITLE
Tabs: Buttons, UserInterfce, Notifications crash

### ISSUE THREAD

**Issue by ShevT** [crdroidandroid/android_packages_apps_crDroidSettings#869]
```
02-13 14:44:03.308 14396 14396 E AndroidRuntime: FATAL EXCEPTION: main
02-13 14:44:03.308 14396 14396 E AndroidRuntime: Process: com.android.settings, PID: 14396
02-13 14:44:03.308 14396 14396 E AndroidRuntime: java.lang.ClassCastException: androidx.preference.Preference cannot be cast to androidx.preference.SwitchPreference
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at com.crdroid.settings.fragments.UserInterface.onCreate(UserInterface.java:68)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2939)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:451)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2209)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2120)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1991)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:249)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1237)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:672)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:634)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.setCurrentItem(ViewPager.java:615)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at com.crdroid.settings.PagerSlidingTabStrip$1.onClick(PagerSlidingTabStrip.java:259)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at android.view.View.performClick(View.java:7441)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7418)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at android.view.View.access$3700(View.java:835)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:28677)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7839)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-13 14:44:03.308 14396 14396 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)


02-13 14:44:21.665 14397 14397 E AndroidRuntime: FATAL EXCEPTION: main
02-13 14:44:21.665 14397 14397 E AndroidRuntime: Process: com.android.settings, PID: 14397
02-13 14:44:21.665 14397 14397 E AndroidRuntime: java.lang.ClassCastException: androidx.preference.Preference cannot be cast to androidx.preference.SwitchPreference
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at com.crdroid.settings.fragments.UserInterface.onCreate(UserInterface.java:68)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2939)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:451)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2209)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2120)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1991)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:249)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1237)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:672)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:634)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.setCurrentItem(ViewPager.java:615)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at com.crdroid.settings.PagerSlidingTabStrip$1.onClick(PagerSlidingTabStrip.java:259)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at android.view.View.performClick(View.java:7441)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7418)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at android.view.View.access$3700(View.java:835)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:28677)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7839)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-13 14:44:21.665 14397 14397 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)


02-13 14:44:29.336 14398 14398 E AndroidRuntime: FATAL EXCEPTION: main
02-13 14:44:29.336 14398 14398 E AndroidRuntime: Process: com.android.settings, PID: 14398
02-13 14:44:29.336 14398 14398 E AndroidRuntime: java.lang.ClassCastException: androidx.preference.Preference cannot be cast to androidx.preference.SwitchPreference
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at com.crdroid.settings.fragments.UserInterface.onCreate(UserInterface.java:68)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2939)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:451)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2209)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2120)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1991)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:249)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1237)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:672)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:634)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.setCurrentItem(ViewPager.java:615)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at com.crdroid.settings.PagerSlidingTabStrip$1.onClick(PagerSlidingTabStrip.java:259)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at android.view.View.performClick(View.java:7441)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7418)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at android.view.View.access$3700(View.java:835)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:28677)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7839)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-13 14:44:29.336 14398 14398 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by koron393** [comment]
Me too.

It's happend from src/com/crdroid/settings/fragments/UserInterface.java line 68
"mShowCutoutForce = (SwitchPreference) findPreference(KEY_FORCE_FULL_SCREEN);"

I simply delete line 67 to 70 and rebuild the ROM.

**Comment by ShevT** [comment]
> It's happend from src/com/crdroid/settings/fragments/UserInterface.java line 68
> "mShowCutoutForce = (SwitchPreference) findPreference(KEY_FORCE_FULL_SCREEN);"

Then the problem is in this patch: https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/commit/e075c0435d902bf5e7ff406197275aeecab7f464

**Comment by gwolf2u** [comment]
fixed in https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/commit/4484a8b87c29b53e27305e10b23a4c583ca95e5f
